# Conclusion

The global indicators captured in data from World Bank point to several noticeable trends that are visible globally in the span of roughly the past 70 years. In our analysis, we wanted to capture insights from social, economic, and environmental aspects of global regions, and thus, we focused on these primary topics: mortality rates and life expectancy, literacy and education, GDP & economic conditions, environmental sustainability, and clean water access. 

The countries with the highest mortality rates for infants were in Africa. Additionally, there was a sizable gap between male infants versus female infants, with male infants having a slightly higher infant mortality rate across each country. Factors such as access to clean water and resources for income stability in these regions could be contributing to these high rates. Many African countries had a low % of their population that had safe drinking water, which can have a direct effect on infants. However, at large, a major decrease in mortality rates was seen in all countries of Africa from 1960 to 2020 for adults and infants alike. This was part of a larger trend in improvements in human life across the globe with average life expectancy increases in all 266 countries. In 1960, many countries had an average life expectancy close to 30 for males and females while in 2020, there were none below 50. This points to advancements in living conditions in all countries, specifically developing nations, as evident through a decrease in mortality rates and an increase in life expectancy.

Accessibility to education also has been a vital global indicator of improvement. In the past, the disparity in education due to income levels can be noticed in many countries with a low Gross Domestic Product (GDP) and GDP per capital level.  In recent years, due to the digitization of education and increased access to the internet in all regions of the globe, the disparity seems to be decreasing. While many high-income countries had roughly the same % of literacy rates from 2000 to 2020, countries that fell into the low to middle-income bracket had a marked increase during the same period. Females still had lower overall literacy % across the board, however, lower to middle-income countries had the highest % increase for female education. Access to technology and a modern viewpoint on the female workforce has fueled a more inclusive education environment while countries also have a more robust economy as evident in the global rise in GDP for all nations. 

Finally, environmental aspects are critical due to the global climate crisis and the disproportional impact of natural disasters and conflicts. Nations with GDP that is reliant on agricultural commodities dedicated a large % of their area to farms and relatively little to forests and other natural These agrarian nations also had high fertilizer consumption due to the vast amount of arable land. areas. Fossil fuel usage was also high, possibly as many regions lacked a sufficient renewable source of energy, and consequently, CO2 emissions were higher as result. These environmental indicators may help derive better sustainability goals and improve the local living environment. 

